apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx 
  labels:
    app: nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ch04/nginx:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: BACKEND_HOST
          value: 127.0.0.1:8080
