version: "3"
services:
  echo:
    image: gihyodocker/echo:latest 
    deploy:
      replicas: 3
      placement:
        constraints: [node.role != manager]
    networks:
      - loadtest 

networks:
  loadtest:
    external: true
