apiVersion: v1
kind: Service
metadata:
  name: echo 
spec:
  selector:
    app: echo 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: http 
    nodePort: 30080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: nginx
        image: gihyodocker/nginx:latest
        env:
        - name: BACKEND_HOST
          value: localhost:8080
        - name: LOG_STDOUT
          value: "true"
        ports:
        - name: http
          containerPort: 80
      - name: echo
        image: gihyodocker/echo:latest
        ports:
        - containerPort: 8080
